### ISSUE TITLE
Support ERC tokens 

### ISSUE THREAD

**Issue by AliNik4n** [hiero-ledger/hiero-mirror-node-explorer#1500]
### Problem

As ERC tokens are coming to our network, we will need to start supporting ERC tokens in Hashscan to improve user experience and ensure feature parity between HTS and ERC tokens within our explorer. 

Problems: 
- EVM side of Hedera is growing, we have multiple partners who are opting to use ERCs and wallets on our ecosystem are starting to support ERC tokens.
- Chainlink is coming onboard with an ERC token, and we already have more partners who are focusing exclusively on supporting ERC tokens. This will increase the need of supporting ERC tokens on Hedera Mirrornode explorer.
- EVM developers and users coming from EVM chains to Hedera, expect a similar experience when interacting with our explorer, that includes exposing ERC tokens on the explorer similar to EVM explorers 
- Hedera developers, who are experimenting Hedera’s EVM are expecting explorer to support ERC tokens the same way it is supporting HTS tokens, this can be very tricky as concept of ERCs is not exposed or stored in Mirrornode APIs.

### Solution

Build the functionality in Hashscan to display ERC tokens, provide feature parity between Hashscan and EVM explorers and improve support for HTS tokens. That includes: 
- Token search - ability to search an ERC token 
- Token balances of ERC tokens within an account 
- Contracts - indication of what contracts is an ERC token contract) 
- Tx history 

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1531
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1534
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1538
```

**Comment by SimiHunjan** [comment]
Should have a json file by the end of this week and final after the next sprint

**Comment by gregscullard** [comment]
note https://polygonscan.com/token/0xfa8d28b0ccb4d0a1c7c9ee23d6514274903f3553 (NFT) provides great insights into token contracts (erc-20 and 721), including transactions but also holders and inventory (NFTs).

For ERC-20 https://polygonscan.com/token/0x7ceb23fd6bc0add59e62ac25578270cff1b9f619#balances

**Comment by svienot** [comment]
Closing this issue since we are done leveraging the files generated by the erc-registry indexer, and Explorer cannot do more given the current infrastructure. In particular, the ERC-1155 interface does not provide any way to enumerate the tokens implemented by a contract, so the explorer has no means to discover those and seek their metadata.
